# Goreleaser configuration file

project_name: did-resolver

env:
  - GO111MODULE=on

before:
  hooks:
    - make clean
    - make tidy
    - make swagger

builds:
  - 
    env:
      - CGO_ENABLED=1
    main: main.go
    binary: did-resolver
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/cheqd/did-resolver/cmd.version={{ .Version }}
      - -X github.com/cheqd/did-resolver/cmd.Commit={{ .Commit }}

archives:
  - id: release-archives
    format: tar.gz
    wrap_in_directory: false
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github
  sort: asc
  groups:
  - title: Features
    regexp: "^.*feat[(\\w)]*:+.*$"
    order: 0
  - title: 'Fixes'
    regexp: "^.*fix[(\\w)]*:+.*$"
    order: 1
  - title: 'Performance Improvements'
    regexp: "^.*perf[(\\w)]*:+.*$"
    order: 2
  - title: 'Build Improvements'
    regexp: "^.*build[(\\w)]*:+.*$"
    order: 3
  - title: 'Security'
    regexp: "^.*build[(\\w)]*:+.*$"
    order: 4
  - title: 'Other changes'
    order: 999
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^ci'
      - '^refactor'
      - '^revert'
      - '^style'

release:
  github:
    owner: cheqd
    name: did-resolver
  
  draft: false
  prerelease: auto
  mode: append
  header: |
    # Release Notes for {{.ProjectName}} v{{.Version}}
