// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Cheqd Foundation Limited",
            "url": "https://cheqd.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://github.com/cheqd/did-resolver/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/1.0/identifiers/{did}": {
            "get": {
                "description": "Fetch DID Document (\"DIDDoc\") from cheqd network ledger",
                "consumes": [
                    "application/did+ld+json",
                    "application/ld+json",
                    "application/did+json"
                ],
                "produces": [
                    "application/did+ld+json",
                    "application/ld+json",
                    "application/did+json"
                ],
                "tags": [
                    "DID Resolution"
                ],
                "summary": "Resolve DID Document on did:cheqd",
                "parameters": [
                    {
                        "type": "string",
                        "description": "DID Unique Identifier",
                        "name": "did",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.DidResolution"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.DidResolution"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.DidResolution"
                        }
                    },
                    "406": {
                        "description": "Not Acceptable",
                        "schema": {
                            "$ref": "#/definitions/types.DidResolution"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.DidResolution"
                        }
                    }
                }
            }
        },
        "/1.0/identifiers/{did}/resources/all": {
            "get": {
                "description": "Get a list of all collection resources metadata",
                "produces": [
                    "*/*"
                ],
                "tags": [
                    "Dereferencing"
                ],
                "summary": "Collection resources",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Resource collection id. DID Doc Id",
                        "name": "did",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The requested media type of the DID document representation or DID resolution result. ",
                        "name": "accept",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    },
                    "406": {
                        "description": "Not Acceptable",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    }
                }
            }
        },
        "/1.0/identifiers/{did}/resources/{resourceId}": {
            "get": {
                "description": "Get specific Resource within a DIDoc Resource Collection",
                "produces": [
                    "*/*"
                ],
                "tags": [
                    "Resource Resolution"
                ],
                "summary": "Fetch specific Resource",
                "parameters": [
                    {
                        "type": "string",
                        "description": "DID Unique",
                        "name": "did",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "DID Resource identifier",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "application/did+ld+json",
                            "application/ld+json",
                            "application/did+json"
                        ],
                        "type": "string",
                        "description": "The requested media type of the DID document representation or DID resolution result. ",
                        "name": "accept",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    },
                    "406": {
                        "description": "Not Acceptable",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    }
                }
            }
        },
        "/1.0/identifiers/{did}/resources/{resourceId}/metadata": {
            "get": {
                "description": "Get metadata for a specific Resource within a DIDoc Resource Collection",
                "produces": [
                    "*/*"
                ],
                "tags": [
                    "Resource Resolution"
                ],
                "summary": "Fetch specific Resource metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "DID Unique Identifier",
                        "name": "did",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Resource Unique Identifier",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "application/did+ld+json",
                            "application/ld+json",
                            "application/did+json"
                        ],
                        "type": "string",
                        "description": "Accept header",
                        "name": "accept",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    },
                    "406": {
                        "description": "Not Acceptable",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    }
                }
            }
        },
        "/1.0/identifiers/{did}{fragmentId}": {
            "get": {
                "description": "Fetch DID Document (\"DIDDoc\") from cheqd network ledger with dereferencing",
                "consumes": [
                    "application/did+ld+json",
                    "application/ld+json",
                    "application/did+json"
                ],
                "produces": [
                    "application/did+ld+json",
                    "application/ld+json",
                    "application/did+json"
                ],
                "tags": [
                    "DID Resolution"
                ],
                "summary": "Resolve DID Document with dereferencing on did:cheqd",
                "parameters": [
                    {
                        "type": "string",
                        "description": "DID Unique Identifier",
                        "name": "did",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "` + "`" + `#` + "`" + ` + Fragment Identifier",
                        "name": "fragmentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Service Identifier",
                        "name": "service",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    },
                    "406": {
                        "description": "Not Acceptable",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.ContentType": {
            "type": "string",
            "enum": [
                "application/did+json",
                "application/did+ld+json",
                "application/ld+json",
                "application/json"
            ],
            "x-enum-varnames": [
                "DIDJSON",
                "DIDJSONLD",
                "JSONLD",
                "JSON"
            ]
        },
        "types.DereferencedResource": {
            "type": "object",
            "properties": {
                "checksum": {
                    "type": "string"
                },
                "created": {
                    "type": "string"
                },
                "mediaType": {
                    "type": "string"
                },
                "nextVersionId": {
                    "type": "string"
                },
                "previousVersionId": {
                    "type": "string"
                },
                "resourceCollectionId": {
                    "type": "string"
                },
                "resourceId": {
                    "type": "string"
                },
                "resourceName": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                },
                "resourceURI": {
                    "type": "string"
                }
            }
        },
        "types.DereferencingMetadata": {
            "type": "object",
            "properties": {
                "contentType": {
                    "$ref": "#/definitions/types.ContentType"
                },
                "did": {
                    "$ref": "#/definitions/types.DidProperties"
                },
                "error": {
                    "type": "string"
                },
                "retrieved": {
                    "type": "string"
                }
            }
        },
        "types.DidDereferencing": {
            "type": "object",
            "properties": {
                "@context": {
                    "type": "string",
                    "example": "https://w3id.org/did-resolution/v1"
                },
                "contentMetadata": {
                    "$ref": "#/definitions/types.ResolutionDidDocMetadata"
                },
                "contentStream": {},
                "dereferencingMetadata": {
                    "$ref": "#/definitions/types.DereferencingMetadata"
                }
            }
        },
        "types.DidDoc": {
            "type": "object",
            "properties": {
                "@context": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "alsoKnownAs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "assertionMethod": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "authentication": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "capabilityInvocation": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "capability_delegation": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "controller": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "keyAgreement": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "service": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Service"
                    }
                },
                "verificationMethod": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.VerificationMethod"
                    }
                }
            }
        },
        "types.DidProperties": {
            "type": "object",
            "properties": {
                "didString": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "methodSpecificId": {
                    "type": "string"
                }
            }
        },
        "types.DidResolution": {
            "type": "object",
            "properties": {
                "@context": {
                    "type": "string"
                },
                "didDocument": {
                    "$ref": "#/definitions/types.DidDoc"
                },
                "didDocumentMetadata": {
                    "$ref": "#/definitions/types.ResolutionDidDocMetadata"
                },
                "didResolutionMetadata": {
                    "$ref": "#/definitions/types.ResolutionMetadata"
                }
            }
        },
        "types.ResolutionDidDocMetadata": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "deactivated": {
                    "type": "boolean"
                },
                "linkedResourceMetadata": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.DereferencedResource"
                    }
                },
                "updated": {
                    "type": "string"
                },
                "versionId": {
                    "type": "string"
                }
            }
        },
        "types.ResolutionMetadata": {
            "type": "object",
            "properties": {
                "contentType": {
                    "$ref": "#/definitions/types.ContentType"
                },
                "did": {
                    "$ref": "#/definitions/types.DidProperties"
                },
                "error": {
                    "type": "string"
                },
                "retrieved": {
                    "type": "string"
                }
            }
        },
        "types.Service": {
            "type": "object",
            "properties": {
                "@context": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "serviceEndpoint": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "types.VerificationMethod": {
            "type": "object",
            "properties": {
                "@context": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "controller": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "publicKeyJwk": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "publicKeyMultibase": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.x",
	Host:             "https://resolver.cheqd.net",
	BasePath:         "/1.0/identifiers",
	Schemes:          []string{"http", "https"},
	Title:            "DID Resolver for did:cheqd method",
	Description:      "Universal Resolver driver for did:cheqd method",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
