// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Cheqd Foundation Limited",
            "url": "https://cheqd.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://github.com/cheqd/did-resolver/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/{did}": {
            "get": {
                "description": "Fetch DID Document (\"DIDDoc\") from cheqd network",
                "consumes": [
                    "application/did+ld+json",
                    "application/ld+json",
                    "application/did+json"
                ],
                "produces": [
                    "application/did+ld+json",
                    "application/ld+json",
                    "application/did+json"
                ],
                "tags": [
                    "DID Resolution"
                ],
                "summary": "Resolve DID Document on did:cheqd",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Full DID with unique identifier",
                        "name": "did",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Service Type",
                        "name": "service",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "#Fragment",
                        "name": "fragmentId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Version",
                        "name": "versionId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.DidResolution"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    },
                    "406": {
                        "description": "Not Acceptable",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    }
                }
            }
        },
        "/{did}/metadata": {
            "get": {
                "description": "Get metadata for all Resources within a DID Resource Collection",
                "consumes": [
                    "application/did+ld+json",
                    "application/ld+json",
                    "application/did+json"
                ],
                "produces": [
                    "application/did+ld+json",
                    "application/ld+json",
                    "application/did+json"
                ],
                "tags": [
                    "Resource Resolution"
                ],
                "summary": "Fetch metadata for all Resources",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Full DID with unique identifier",
                        "name": "did",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    },
                    "406": {
                        "description": "Not Acceptable",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    }
                }
            }
        },
        "/{did}/resources/{resourceId}": {
            "get": {
                "description": "Get specific Resource within a DID Resource Collection",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "*/*"
                ],
                "tags": [
                    "Resource Resolution"
                ],
                "summary": "Fetch specific Resource",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Full DID with unique identifier",
                        "name": "did",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Resource-specific unique-identifier",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "integer"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    },
                    "406": {
                        "description": "Not Acceptable",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    }
                }
            }
        },
        "/{did}/resources/{resourceId}/metadata": {
            "get": {
                "description": "Get metadata for a specific Resource within a DID Resource Collection",
                "consumes": [
                    "application/did+ld+json",
                    "application/ld+json",
                    "application/did+json"
                ],
                "produces": [
                    "application/did+ld+json",
                    "application/ld+json",
                    "application/did+json"
                ],
                "tags": [
                    "Resource Resolution"
                ],
                "summary": "Fetch Resource-specific metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Full DID with unique identifier",
                        "name": "did",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Resource-specific unique identifier",
                        "name": "resourceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.DidDereferencing"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    },
                    "406": {
                        "description": "Not Acceptable",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    }
                }
            }
        },
        "/{did}/version/{versionId}": {
            "get": {
                "description": "Fetch specific all version of a DID Document (\"DIDDoc\") for a given DID\nFetch specific all versions of a DID Document (\"DIDDoc\") for a given DID",
                "consumes": [
                    "application/did+ld+json",
                    "application/ld+json",
                    "application/did+json",
                    "application/did+ld+json",
                    "application/ld+json",
                    "application/did+json"
                ],
                "produces": [
                    "application/did+ld+json",
                    "application/ld+json",
                    "application/did+json",
                    "application/did+ld+json",
                    "application/ld+json",
                    "application/did+json"
                ],
                "tags": [
                    "DID Resolution",
                    "DID Resolution"
                ],
                "summary": "Resolve DID Document Versions on did:cheqd",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Full DID with unique identifier",
                        "name": "did",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "version of a DID document",
                        "name": "versionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Full DID with unique identifier",
                        "name": "did",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.DidDereferencing"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "contentStream": {
                                            "$ref": "#/definitions/types.DereferencedDidVersionsList"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    },
                    "406": {
                        "description": "Not Acceptable",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    }
                }
            }
        },
        "/{did}/versions": {
            "get": {
                "description": "Fetch specific all version of a DID Document (\"DIDDoc\") for a given DID\nFetch specific all versions of a DID Document (\"DIDDoc\") for a given DID",
                "consumes": [
                    "application/did+ld+json",
                    "application/ld+json",
                    "application/did+json",
                    "application/did+ld+json",
                    "application/ld+json",
                    "application/did+json"
                ],
                "produces": [
                    "application/did+ld+json",
                    "application/ld+json",
                    "application/did+json",
                    "application/did+ld+json",
                    "application/ld+json",
                    "application/did+json"
                ],
                "tags": [
                    "DID Resolution",
                    "DID Resolution"
                ],
                "summary": "Resolve DID Document Versions on did:cheqd",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Full DID with unique identifier",
                        "name": "did",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "version of a DID document",
                        "name": "versionId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Full DID with unique identifier",
                        "name": "did",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.DidDereferencing"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "contentStream": {
                                            "$ref": "#/definitions/types.DereferencedDidVersionsList"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    },
                    "406": {
                        "description": "Not Acceptable",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/types.IdentityError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_cheqd_cheqd-node_x_did_types.Metadata": {
            "type": "object",
            "properties": {
                "created": {
                    "description": "created is the timestamp of the creation of the DID Document.\nFormat: RFC3339\nExample: 2021-03-10T15:16:17Z",
                    "type": "string"
                },
                "deactivated": {
                    "description": "deactivated is a flag that indicates whether the DID Document is deactivated.\nDefault: false",
                    "type": "boolean"
                },
                "next_version_id": {
                    "description": "next_version_id is the version identifier of the next version of the DID Document.\nFormat: UUID\nExample: 123e4567-e89b-12d3-a456-426655440000",
                    "type": "string"
                },
                "previous_version_id": {
                    "description": "previous_version_id is the version identifier of the previous version of the DID Document.\nFormat: UUID\nExample: 123e4567-e89b-12d3-a456-426655440000",
                    "type": "string"
                },
                "updated": {
                    "description": "updated is the timestamp of the last update of the DID Document.\nFormat: RFC3339\nExample: 2021-03-10T15:16:17Z",
                    "type": "string"
                },
                "version_id": {
                    "description": "version_id is the version identifier of the DID Document.\nFormat: UUID\nExample: 123e4567-e89b-12d3-a456-426655440000",
                    "type": "string"
                }
            }
        },
        "github_com_cheqd_did-resolver_types.DidDoc": {
            "type": "object",
            "properties": {
                "@context": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "https://www.w3.org/ns/did/v1"
                    ]
                },
                "alsoKnownAs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "assertionMethod": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "authentication": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "did:cheqd:testnet:55dbc8bf-fba3-4117-855c-1e0dc1d3bb47#key-1"
                    ]
                },
                "capabilityInvocation": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "capability_delegation": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "controller": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "did:cheqd:testnet:55dbc8bf-fba3-4117-855c-1e0dc1d3bb47"
                    ]
                },
                "id": {
                    "type": "string",
                    "example": "did:cheqd:testnet:55dbc8bf-fba3-4117-855c-1e0dc1d3bb47"
                },
                "keyAgreement": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "service": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_cheqd_did-resolver_types.Service"
                    }
                },
                "verificationMethod": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_cheqd_did-resolver_types.VerificationMethod"
                    }
                }
            }
        },
        "github_com_cheqd_did-resolver_types.Service": {
            "type": "object",
            "properties": {
                "@context": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string",
                    "example": "did:cheqd:testnet:55dbc8bf-fba3-4117-855c-1e0dc1d3bb47#service-1"
                },
                "serviceEndpoint": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "https://example.com/endpoint/8377464"
                    ]
                },
                "type": {
                    "type": "string",
                    "example": "did-communication"
                }
            }
        },
        "github_com_cheqd_did-resolver_types.VerificationMethod": {
            "type": "object",
            "properties": {
                "@context": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "controller": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "publicKeyBase58": {
                    "type": "string"
                },
                "publicKeyJwk": {},
                "publicKeyMultibase": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "types.ContentType": {
            "type": "string",
            "enum": [
                "application/did+json",
                "application/did+ld+json",
                "application/ld+json",
                "application/json"
            ],
            "x-enum-varnames": [
                "DIDJSON",
                "DIDJSONLD",
                "JSONLD",
                "JSON"
            ]
        },
        "types.DereferencedDidVersionsList": {
            "type": "object",
            "properties": {
                "versions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_cheqd_cheqd-node_x_did_types.Metadata"
                    }
                }
            }
        },
        "types.DereferencedResource": {
            "type": "object",
            "properties": {
                "checksum": {
                    "type": "string",
                    "example": "a95380f460e63ad939541a57aecbfd795fcd37c6d78ee86c885340e33a91b559"
                },
                "created": {
                    "type": "string",
                    "example": "2021-09-01T12:00:00Z"
                },
                "mediaType": {
                    "type": "string",
                    "example": "image/png"
                },
                "nextVersionId": {
                    "type": "string",
                    "example": "d4829ac7-4566-478c-a408-b44767eddadc"
                },
                "previousVersionId": {
                    "type": "string",
                    "example": "ad7a8442-3531-46eb-a024-53953ec6e4ff"
                },
                "resourceCollectionId": {
                    "type": "string",
                    "example": "55dbc8bf-fba3-4117-855c-1e0dc1d3bb47"
                },
                "resourceId": {
                    "type": "string",
                    "example": "398cee0a-efac-4643-9f4c-74c48c72a14b"
                },
                "resourceName": {
                    "type": "string",
                    "example": "Image Resource"
                },
                "resourceType": {
                    "type": "string",
                    "example": "Image"
                },
                "resourceURI": {
                    "type": "string",
                    "example": "did:cheqd:testnet:55dbc8bf-fba3-4117-855c-1e0dc1d3bb47/resources/398cee0a-efac-4643-9f4c-74c48c72a14b"
                }
            }
        },
        "types.DereferencingMetadata": {
            "type": "object",
            "properties": {
                "contentType": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.ContentType"
                        }
                    ],
                    "example": "application/did+ld+json"
                },
                "did": {
                    "$ref": "#/definitions/types.DidProperties"
                },
                "error": {
                    "type": "string"
                },
                "retrieved": {
                    "type": "string",
                    "example": "2021-09-01T12:00:00Z"
                }
            }
        },
        "types.DidDereferencing": {
            "type": "object",
            "properties": {
                "@context": {
                    "type": "string",
                    "example": "https://w3id.org/did-resolution/v1"
                },
                "contentMetadata": {
                    "$ref": "#/definitions/types.ResolutionDidDocMetadata"
                },
                "contentStream": {},
                "dereferencingMetadata": {
                    "$ref": "#/definitions/types.DereferencingMetadata"
                }
            }
        },
        "types.DidProperties": {
            "type": "object",
            "properties": {
                "didString": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "methodSpecificId": {
                    "type": "string"
                }
            }
        },
        "types.DidResolution": {
            "type": "object",
            "properties": {
                "@context": {
                    "type": "string"
                },
                "didDocument": {
                    "$ref": "#/definitions/github_com_cheqd_did-resolver_types.DidDoc"
                },
                "didDocumentMetadata": {
                    "$ref": "#/definitions/types.ResolutionDidDocMetadata"
                },
                "didResolutionMetadata": {
                    "$ref": "#/definitions/types.ResolutionMetadata"
                }
            }
        },
        "types.IdentityError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "contentType": {
                    "$ref": "#/definitions/types.ContentType"
                },
                "did": {
                    "type": "string"
                },
                "internal": {},
                "isDereferencing": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "types.ResolutionDidDocMetadata": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string",
                    "example": "2021-09-01T12:00:00Z"
                },
                "deactivated": {
                    "type": "boolean",
                    "example": false
                },
                "linkedResourceMetadata": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.DereferencedResource"
                    }
                },
                "updated": {
                    "type": "string",
                    "example": "2021-09-10T12:00:00Z"
                },
                "versionId": {
                    "type": "string",
                    "example": "4979BAF49599FEF0BAD5ED0849FDD708156761EBBC8EBE78D0907F8BECC9CB2E"
                }
            }
        },
        "types.ResolutionMetadata": {
            "type": "object",
            "properties": {
                "contentType": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/types.ContentType"
                        }
                    ],
                    "example": "application/did+ld+json"
                },
                "did": {
                    "$ref": "#/definitions/types.DidProperties"
                },
                "error": {
                    "type": "string"
                },
                "retrieved": {
                    "type": "string",
                    "example": "2021-09-01T12:00:00Z"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "resolver.cheqd.net",
	BasePath:         "/1.0/identifiers",
	Schemes:          []string{"https", "http"},
	Title:            "DID Resolver for did:cheqd method",
	Description:      "Universal Resolver driver for did:cheqd method",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
