name: "Lint"
on:
  workflow_call:
defaults:
  run:
    shell: bash


jobs:

  md-link-check:
    name: "Broken Markdown links"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Markdown link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: '.github/linters/mlc_config.json'
          use-quiet-mode: 'yes'

  go-lint:
    # We can't use VALIDATE_GO from super linter because of this issue:
    # https://github.com/github/super-linter/issues/143
    name: "Golang Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          # cache = false cause there is an open issue related to "File exists" error.
          # https://github.com/golangci/golangci-lint-action/issues/807
          cache: false

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.6
          args: --config .github/linters/.golangci.yaml

  super-lint:
    name: "Super Linter"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required to fetch version

    - name: Run Super Linter
      uses: super-linter/super-linter/slim@v7
      env:
        IGNORE_GITIGNORED_FILES: true
        DEFAULT_BRANCH: main
        LINTER_RULES_PATH: '.github/linters'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG_LEVEL: WARN
        VALIDATE_ALL_CODEBASE: true
        MULTI_STATUS: true

        VALIDATE_BASH: true
        VALIDATE_DOCKERFILE_HADOLINT: true
        VALIDATE_ENV: true
        VALIDATE_GITHUB_ACTIONS: true
        VALIDATE_JSONC: true
        VALIDATE_MARKDOWN: true
        VALIDATE_OPENAPI: true
        VALIDATE_PYTHON_PYLINT: true
        VALIDATE_YAML: true
