name: "Deploy"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:

  deploy-staging:
    name: "Staging Deploy"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}
    environment:
      name: staging
      url: https://resolver-staging.cheqd.net

    steps:
      - name: Install DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login --expiry-seconds 600

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: did-resolver-staging

      - name: Load Docker image
        run: docker image load --input did-resolver-staging.tar

      - name: Push staging image to DOCR
        run: docker image push --all-tags registry.digitalocean.com/${{ env.IMAGE_NAME }}

  release-staging:
    name: "Release Staging Docker image"
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'develop' }}
    env:
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: did-resolver-staging

      - name: Load Docker image
        run: docker image load --input did-resolver-staging.tar

      - name: Push image to GitHub Container Registry
        run: docker image push --all-tags ghcr.io/${{ env.IMAGE_NAME }}
